# Generated by Django 4.2.4 on 2023-09-05 17:07

from django.db import migrations, models
import main_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_projeto_imagem_redimensionada_alter_projeto_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem_redimensionada',
            field=models.ImageField(blank=True, null=True, upload_to=main_site.models.sendred),
        ),
    ]
